DROP TABLE IF EXISTS users CASCADE;
DROP TABLE IF EXISTS chats CASCADE;
DROP TABLE IF EXISTS rooms CASCADE;
DROP TABLE IF EXISTS favorites CASCADE;
DROP TABLE IF EXISTS avatars CASCADE;
DROP TABLE IF EXISTS languages CASCADE;
DROP TABLE IF EXISTS messages CASCADE;

CREATE TABLE users (
  id SERIAL PRIMARY KEY NOT NULL,
  username VARCHAR(255) UNIQUE NOT NULL,
  password VARCHAR(255) NOT NULL,
  email VARCHAR(255) UNIQUE NOT NULL,
  avatar VARCHAR(255) NOT NULL REFERENCES avatars(id),
  language_id INTEGER REFERENCES languages(id)
)

CREATE TABLE rooms (
  id SERIAL PRIMARY KEY NOT NULL,
  room_name VARCHAR(255) NOT NULL,
  permission BOOLEAN DEFAULT FALSE NOT NULL
)

CREATE TABLE avatars (
  id SERIAL PRIMARY KEY NOT NULL
  avatar_name VARCHAR(255) UNIQUE NOT NULL
)

CREATE TABLE languages (
  id SERIAL PRIMARY KEY NOT NULL
  lanbuage_name VARCHAR(255) UNIQUE NOT NULL
)

CREATE TABLE messages (
  id SERIAL PRIMARY KEY NOT NULL,
  message VARCHAR(255) NOT NULL,
  sender_id INTEGER REFERENCES NOT NULL,
  room_id REFERENCES rooms(id) CASCADE NOT NULL,
  created_at DATE NOT NULL DEFAULT CURRENT_DATE,
  recipient_id INTEGER REFERENCES NOT NULL,
)

CREATE TABLE favorites (
  id SERIAL PRIMARY KEY NOT NULL
  followed INTEGER REFERENCES NOT NULL,
  following INTEGER REFERENCES NOT NULL,
)

CREATE TABLE room_members (
  id SERIAL PRIMARY KEY NOT NULL
  uset_id REFERENCES users(id)
  rooms_id REFERENCES rooms(id)
)